### ISSUE TITLE
cf-gitbot crosslinking issues to pivotal tracker is broken for this project (and other projects?)

### ISSUE THREAD

**Issue by kdvolder** [pivotal-cf-experimental/lattice-cli#16]
I create an issue on github and cf-gitbot 'helpfully' creates an issue in the 'secret' pivotal tracker.

While I can navigate to the issue and see it... it is otherwise totally 'read only'. 

I can't comment on it or subscribe to get notified of issue activity.

 So how am going to follow up when someone asks a question?

**Comment by davidwadden** [comment]
Not sure what happened to the original tracker story - I created a chore to investigate why this isn't working right -- https://www.pivotaltracker.com/story/show/90416534

**Comment by davidwadden** [comment]
@kdvolder we spoke with the maintainers of the cf-gitbot, and learned it does not support cross-posting comments between tracker and github, it simply labels the tracker issue with 'new-activity' when new comments are posted on github.  i would also like to have this functionality, but, this is what we'll have to live with

closing this issue.

**Comment by menicosia** [comment]
Hi @kdvolder,

@davidwadden is correct, but I just wanted to explain/expand a little bit: The primary place that Pivotal uses to orchestrate with the community is here, on GitHub. Internally, we use Tracker to organize and manage our work load. We provide visibility into those trackers for public projects so that people can see where and when the effort has been prioritized.

Tracker's not meant to be a part of the communication mechanism, we'll always conduct our conversations here on GitHub. Since our developers organize their lives out of Tracker, the cf-bots troll GitHub and mark up existing stories with 'new-activity' to alert the PMs and Devs that there are new updates on GitHub to review. Sometimes we don't get a response for days or weeks. The 'new-activity' flag helps ensure we don't lose track of these.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
